defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      path: ''
      type: posts

    values:
      layout: post
      parent: blog
      div_id: blost

  -
    scope:
      path: projects

    values:
      layout: project
      parent: projects

permalink: pretty
exclude:
  - scratch
  - vendor
